# Dataset
We are using tiny shakespeare dataset.<br>
Let's download the dataset!

In [2]:
import requests

url = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
response = requests.get(url)
response.raise_for_status() # Chek for any errors during the request
with open("./input.txt", "wb") as file:
    file.write(response.content)


We now inspect the dataset

In [2]:
with open("./input.txt", "r", encoding="utf-8") as file:
    text = file.read()

In [3]:
print(f"[INFO] Length of dataset in characters: {len(text)}")

[INFO] Length of dataset in characters: 1115394


Let's look at the first 1000 characters

In [4]:
print(f"[INFO] First 1000 characters:\n\n{text[:1000]}")

[INFO] First 1000 characters:

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for brea

Get all unique characters that occur in the text

In [5]:
chars = sorted(list(set(text)))
vocab_size = len(chars)

print(f"[INFO] Vocabulary size: {vocab_size}, All unique chars:\n")
print(''.join(chars))

[INFO] Vocabulary size: 65, All unique chars:


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz


Now we are creating mapping from characters to integers and reverse. <br>
We are basically build tokenizer, very simple one.<br> 
There are many other solutions that are used in practice like (different schemas and vocabularies):
- Google's : __[sentancepiece](https://github.com/google/sentencepiece)__ - sub-word units tokenizer
- OpenAI's : __[tiktoken](https://github.com/openai/tiktoken)__ - byte pair encoding __[(BPE)](https://en.wikipedia.org/wiki/Byte_pair_encoding)__ tokenizer

Keep in mind that there is a trad-off. If you have a large vocabulary your sentence encoding will be smaller (list of few integers).<br>
Where as, if you have a small vocabulary size your encoding of the sentence will bi bigger (large list of integers).  

In [6]:
stoi = { ch:i for i, ch in enumerate(chars) }
itos = { i:ch for i, ch in enumerate(chars) }

# Encoder: take a string and outputs a list of integers
encode = lambda s: [stoi[c] for c in s]
# Decoder: take a list of integers and outputs a string
decode = lambda l: ''.join([itos[i] for i in l])

# Example:
print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


Let's now encode/tokenize the entire text dataset and store it as torch.Tensor

In [7]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)

print(f"[INFO] Shape of encoded text: {data.shape}, Variable type: {data.dtype}")
print(data)

[INFO] Shape of encoded text: torch.Size([1115394]), Variable type: torch.int64
tensor([18, 47, 56,  ..., 45,  8,  0])


1000 characters that we looked at earlier will look like tis to our GPT model

In [8]:
print(data[:1000])

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
        47, 59, 57,  1, 47, 57,  1, 41, 

Let's now slit up our data into train and validation sets.<br>
First 90% of data will be train and rest validation.

In [9]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

Define maximum input/context length.<br>
Time dimension of the tensors that are going to be feed into the Transformer.

In [10]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

We train on all of the block_size (8) examples with context between 1 all the way to context of block_size (8).<br>
We want to make the transformer network be used to seeing contexts from as little as one all the way to block_size.<br>
Transformer will never receive more than block size inputs when it's predicting the next character.

In [11]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"When input is {context} the target is: {target}")

When input is tensor([18]) the target is: 47
When input is tensor([18, 47]) the target is: 56
When input is tensor([18, 47, 56]) the target is: 57
When input is tensor([18, 47, 56, 57]) the target is: 58
When input is tensor([18, 47, 56, 57, 58]) the target is: 1
When input is tensor([18, 47, 56, 57, 58,  1]) the target is: 15
When input is tensor([18, 47, 56, 57, 58,  1, 15]) the target is: 47
When input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target is: 58


Create **Batches** of data.
- batch_size : how many independent sequences will we process in parallel
- block_size : what is the maximum context length for predictions

In [12]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):
    '''Generate a small batch of data of inputs x and targets y.'''
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch(split="train")
print(f"Input: {xb.shape}")
print(xb)
print(f"Targets: {yb.shape}")
print(yb)

print("-"*30)

for b in range(batch_size): # Batch dimension
    for t in range(block_size): # Time dimension
        context = xb[b, :t+1]
        target = yb[b, t]
        print(f"When input is: {context}, the target is: {target}")


Input: torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
Targets: torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
------------------------------
When input is: tensor([24]), the target is: 43
When input is: tensor([24, 43]), the target is: 58
When input is: tensor([24, 43, 58]), the target is: 5
When input is: tensor([24, 43, 58,  5]), the target is: 57
When input is: tensor([24, 43, 58,  5, 57]), the target is: 1
When input is: tensor([24, 43, 58,  5, 57,  1]), the target is: 46
When input is: tensor([24, 43, 58,  5, 57,  1, 46]), the target is: 43
When input is: tensor([24, 43, 58,  5, 57,  1, 46, 43]), the target is: 39
When input is: tensor([44]), the target is: 53
When input is: tensor([44, 53]), the target 

Our input to the Transformer

In [13]:
print(xb)

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


# NN Model 

First we test the simplest possible model, using only one character to predict he next one.<br>
After that we are improving the model by allowing the characters to talk to each other.<br>
Using more characters, so they can understand/find the context, to predict the next one.

In [19]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size) -> None:
        super().__init__()
        # Each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        # idx and targets are both (B, T) tensor of integers
        logits = self.token_embedding_table(idx) # (B, T, C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx


    
m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx= torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)

SKIcLT;AcELMoTbvZv C?nq-QE33:CJqkOKH-q;:la!oiywkHjgChzbQ?u!3bLIgwevmyFJGUGp
wnYWmnxKWWev-tDqXErVKLgJ


We can guess what the initial loss should be. <br>
Because we have 65 possible outputs, we are expecting -ln(65) to bi our initial loss.

In [18]:
-1*torch.log(torch.tensor(1/65))

tensor(4.1744)

# Training the model

Create a PyTorch optimizer

In [21]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [26]:
from tqdm import tqdm

batch_size = 32
for steps in tqdm(range(10000)):
    # sample a batch of data
    xb, yb = get_batch("train")

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

100%|██████████| 10000/10000 [00:13<00:00, 765.04it/s]

2.3388493061065674


In [27]:
print(decode(m.generate(idx= torch.zeros((1,1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


I ere porna thond g w o 't ysoois, imin'd tiss.
Frer! uleen mail RYor, ye wis, t's icu IETomus; I
Whal!
Too k bapin ivendeser de brd utse mamew'TEnchoun pe, Viven.
orthomave une fr paril!
WI til? farer the ie,
ND pak
Ane s ind.

Th se t aco the maie ave; I unsiveng.
INot f herwit t-d hesoucome. w sun he ne t y:

Finyoyowhes.
ICESTERe; istleceroothethy ou t kis ay:
Ant!

When h, LAUCE:
RDof mee d om throoso-plar, lemy be y, d; h ked; mury Ahehitif o th hen
RDY forord mavare ionglon strarsusf tesi
